#!/bin/bash

SCRIPTS_DIR=".github/pre-commit"

for script in "$SCRIPTS_DIR"/*.sh; do
    # Check if the file is executable
    if [[ -x "$script" ]]; then
        echo "Executing $script..."
        # Execute the script
        "$script"

        # Check the exit status of the script
        if [[ $? -ne 0 ]]; then
            echo "Error executing $script. Aborting commit."
            exit 1
        fi
    fi
done

exit 0