name: Build service

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - name: Lint Go
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Install dependencies
        run: go mod download
        working-directory: backend
      - name: Run tests
        run: gotestsum --junitfile unit-tests.xml
        working-directory: backend
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            backend/unit-tests.xml
